name: TpaPlugin
version: '1.0-SNAPSHOT'
main: de.tim.tpaplugin.TpaPlugin
api-version: '1.20'
commands:
  tpa:
    usage: /tpa <Player>
    description: sends a TPA request to a Player
  tpaaccept:
    usage: /tpaaccept
    description: accept Tpa


